addpath(genpath(fullfile(pwd(), '../../stability'))); % -- include stability folder ------------------------------------
addpath(fullfile(pwd(), 'helpers')); % -- include helper functions -----------------------------------------------------

pars = struct(                                          ...
    'figure_index', 100,                                ...
    'show_unstable_parareal_convergence', true,         ...
    'show_speedup_efficiency_title',      true,         ...
    'scaling_factor', 'total-fine-steps',               ...
    'convergence_norm', Inf,                            ...
    'nfs', 2.^(2:5),                                    ...
    'iters', 0:4,                                       ...
    'generate_figures', false,                          ...
    'num_grid_points', 200                              ...
);

% -- imex integrators --------------------------------------------------------------------------------------------------
domain = struct(                                        ...
    'angles', {{'dispersive'}},                         ...
    'zoom', {{'very-near', 'default', 'far'}},          ...
    'ci', {{@rIMRK1, @rIMRK2, @rIMRK3, @rIMRK4}},       ...
    'fi', {{@rIMRK1, @rIMRK2, @rIMRK3, @rIMRK4}},       ...
    'nc', 1,                                            ...
    'nt', [512 1024 2048 4096]                          ...
);
multiloop(@MLF, domain, pars);